
services:
  neoj4-db:
    image: neo4j:5
    container_name: twitter-neoj4-db
    volumes:
      - ./data:/data
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]