export const MB = 1024 * 1024;

export const PROFILE_IMAGE_SIZE_MULTIPLAYER = 1.5;

export const BACKGROUND_IMAGE_SIZE_MULTIPLAYER = 1.5;

export const MAX_PROFILE_IMAGE_SIZE = MB * PROFILE_IMAGE_SIZE_MULTIPLAYER;

export const MAX_BACKGROUND_IMAGE_SIZE = MB * BACKGROUND_IMAGE_SIZE_MULTIPLAYER;

export const NAME_CHAR_LIMIT = 40;

export const DESCRIPTION_CHAR_LIMIT = 220;

export const LOCATION_CHAR_LIMIT = 30;
