import { getServerSession } from 'next-auth';
import '@/globals.css';

import Providers from '@/components/Providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang='en'>
      <body>
        <Providers session={session}>{children}</Providers>
      </body>
    </html>
  );
}
